### ISSUE TITLE
Difference btw Scratch vs Standard drop field creates bad value(s) during domain check. IRMA 2016 ver.

### ISSUE THREAD

**Issue by jacksonhuang21** [legiongis/clitoolbox#17]
LAND_CHAR
Standard = Small-Scale Features
Scratch = Small Scale Features

RESTRICT_
Standard = Restricted: No third party release
Scratch = Restricted:  No third party disclosure

Standard = Restricted: Affected Program or group concurrence 
Scratch = Restricted:  Affected cultural group concurrence

**Comment by mradamcox** [comment]
@jacksonhuang21 thanks for noting these discrepancies. They should be taken care of now. A couple notes:

I recall that one issue with Small-Scale Features is that the CLI itself was not at the time of this original development completely standardized--some places there was no hyphen. In thinking through the workflow, I don't think making the change that you outlined above will cause any issue (so I did) but it's something to keep in mind.

As for RESTRICT_, looks like the scratch value was a holdover from v1 of the standards, but beyond that there is a discrepancy in NPS published material on exactly what should replace it. "Program" is capitalized in the hard copy standards (here: https://irma.nps.gov/DataStore/Reference/Profile/2206878), however, in the sample GDB published by NPS https://irma.nps.gov/DataStore/Reference/Profile/2206880, it is lower-case. I decided to go with Program, as the hard copy standards take precedent over the GDB, which is just an example implementation of the standards.
