### ISSUE TITLE
Migrate existing pdf documentation to new markdown syntax

### ISSUE THREAD

**Issue by mradamcox** [legiongis/clitoolbox#9]
Existing [pdf documentation](https://github.com/legiongis/clitoolbox/tree/master/documentation) must be migrated into the new markdown files in the readthedocs project. Some files should be recreated exactly, as their content will not change:

- [x] "Graphical Explanation of GUIDs.pdf"
- [x] "Tips for Using CLI Google Earth Files.pdf"

This one should be moved and generally formatted, but its text will be altered so just moving the content will be enough for this ticket.

- [x] "Updating the CLI Feature Table.pdf"

The final pdf, "Using the CLI Toolbox.pdf" is very large and is the main documentation for the toolbox. Some of its contents will need to be changed, but this initial migration effort should endeavor to split its chapters into different files, make its appendices new appendices, etc.

- [x] "Using the CLI Toolbox.pdf"

**Comment by liz387** [comment]
Finished initial migration.
